From node:10
WORKDIR /home/traveler/
RUN apt-get update
COPY ./package.json /home/traveler/package.json
COPY ./yarn.lock /home/traveler/yarn.lock
RUN npm i
COPY ./config/ /home/traveler/config/
COPY ./scripts/ /home/traveler/scripts/
COPY ./src/ /home/traveler/src/
EXPOSE 8000
CMD ["npm","run-script", "startserver"]